# Generated by Django 2.2.5 on 2021-07-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, unique=True)),
                ('class_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(unique=True)),
                ('containment_procedure', models.CharField(max_length=250)),
                ('code_name', models.CharField(max_length=100)),
                ('item_image', models.ImageField(upload_to='Archive/images/item_images')),
                ('object_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Archive.ObjectClass')),
            ],
        ),
    ]
